stages:
  - build
  - prepare
  - deploy


build for prod:
  tags:
    - gr1001
  stage: build
  only:
    -  master
  except:
    changes:
      - "*.conf"
      #- "*.yml" 
  script:
    - echo "start building"   

